### ISSUE TITLE
Building new voice for flite ;HEAPSIZE issue

### ISSUE THREAD

**Issue by signalarun** [happyalu/Flite-TTS-Engine-for-Android#42]
In voice folder/bin/build_flite file there is a variable named HEAPSIZE , what will be its relationship with number of waves.Our clunit unit generation fails giving ran out of storage error. If the above relation is known then the HEAPSIZE shall be adjusted accordingly

**Comment by happyalu** [comment]
Sorry. I hope you have already fixed this. The heapsize is what festvox uses when converting voices to flite. Try increasing it. I'm closing this issue since (a) it has been open for too long, and (b) it isn't related to android port of flite (this project).
