### ISSUE TITLE
how to add mbrola voice to flite -  tts instead of .flitevox files

### ISSUE THREAD

**Issue by omar-adel** [happyalu/Flite-TTS-Engine-for-Android#43]
Hello , 
I want to know 
how to add mbrola voice to flite -  tts ??
this is as I want to add arabic mbrola voice to use them in this android project
and i saw this link :
http://festvox.org/flite/voices/cg/voxdata-v2.0.0/
in 
private final static String VOICE_BASE_URL = "http://festvox.org/flite/voices/cg/voxdata-v2.0.0/";
in Voice.java file

which contain voices whose extension are .flitevox

so how to get mbrola voice to work with me in this project 
instead of  the files in this link 

thanks

**Comment by happyalu** [comment]
Sorry, MBROLA voices aren't supported.

**Comment by omar-adel** [comment]
thanks but what about this 
http://ubuntuforums.org/showthread.php?t=751169

it provides the necessary information about

Make festival TTS use better voices (MBROLA / CMU / HTS)

if you know even any initial steps to get this work for mbrola in android i will be appreciated 

sorry for bad english
