### ISSUE TITLE
extracting phonemes and their respective timings

### ISSUE THREAD

**Issue by charan1595** [happyalu/Flite-TTS-Engine-for-Android#45]
I want to extract phonemes and timings from the utterance structure using hooks provided by flite tts for a talking avatar, how can I do that in android, I am new to this ,any help will be highly appreciated.

**Comment by happyalu** [comment]
This app doesn't implement the functionality to call such tts hooks. I think you can modify code starting from https://github.com/happyalu/Flite-TTS-Engine-for-Android/blob/master/jni/edu_cmu_cs_speech_tts_flite_engine.cc#L375 to add the functionality as you desire. You'll have to add JNI wrappers to add the callback your avatar needs.

**Comment by charan1595** [comment]
Thank you very much,

i tried to compile the app by changing to target=android-22 in project.properties after compiling I installed the obtained FLiteEngine-debug.apk in my samsung galaxy Sduos2 and I could not find any options in manage voices.

**Comment by happyalu** [comment]
The option should show up in Voice input and Output. What seems to be the problem?

**Comment by happyalu** [comment]
Closing old issue.
