### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by jogrimst** [happyalu/Flite-TTS-Engine-for-Android#47]
Hi, I'm trying to build the application according to the README file: https://github.com/happyalu/Flite-TTS-Engine-for-Android/blob/master/README.rst

```
$ ./configure --with-langvox=android --target=armeabiv7a-android

$ make

making in ...
making in include ...
making in src ...
making in src/audio ...
/Users/jogrimst/Android/android-ndk-r11c/toolchains/mipsel-linux-android-4.6/prebuilt/linux-x86/bin/mipsel-linux-android-gcc   -I. -DCST_AUDIO_NONE -I../../include -g -O2 -Wall -fpic -O3 -DANDROID --sysroot=android-ndk-r11c/platforms/android-14/arch-mips    -c auclient.c -o ../../build/mips-android/obj/src/audio/auclient.o
make[2]: android-ndk-r11c/toolchains/mipsel-linux-android-4.6/prebuilt/linux-x86/bin/mipsel-linux-android-gcc: No such file or directory
make[2]: *** [../../build/mips-android/obj/src/audio/auclient.o] Error 1
make[1]: *** [../build/mips-android/obj/src/.make_build_dirs] Error 2
make: *** [build/mips-android/obj//.make_build_dirs] Error 2
```

**Comment by happyalu** [comment]
The paths to gcc seem to have changed between the last NDK version this was
modified for, and now :-)

Just editing the configure script to fix all paths to the Android NDK gcc
should solve this.

**Comment by jogrimst** [comment]
Which configure script are you referring to?

**Comment by happyalu** [comment]
Oh, the "./configure" script that is throwing the error, in the FLITEDIR. If you search for mipsel-linux-android-4.6, in that script, you'll see a handful of lines that need edited.

**Comment by jogrimst** [comment]
I found these two lines:

`ANDROID_NDK_PLATFORM_PATH="$ANDROID_NDK/platforms/android-14"
ANDROID_GCC_VERSION=4.6`

Can I change the Android platform to API 23, or is it required to use API 14?

Do I have to change the GCC version to something else?

**Comment by happyalu** [comment]
I'll need to look up the latest NDK (can do later today). Maybe ANDROID_GCC_VERSION=4.9 fixes it. But in the past the gcc binaries have moved around a lot within the NDK tree, so not sure.

**Comment by happyalu** [comment]
Closing because of #48
