### ISSUE TITLE
Not working in android 13b NDK with flite 2.0.0

### ISSUE THREAD

**Issue by pankajchimple** [happyalu/Flite-TTS-Engine-for-Android#56]
![screenshot from 2016-12-24 12-09-20](https://cloud.githubusercontent.com/assets/16590731/21465648/34cadfec-c9d2-11e6-9706-23c5e2a002df.png)

**Comment by elawed** [comment]
have you found a solution

**Comment by elawed** [comment]
i,m stuck with same problem

**Comment by happyalu** [comment]
This relates to the location of the gcc binaries in the Android NDK, and should be addressed by #48 . Please reopen if this problem continues to exist.
