### ISSUE TITLE
Not able to run my downloaded voice?

### ISSUE THREAD

**Issue by Hanumanth-appface** [happyalu/Flite-TTS-Engine-for-Android#58]
I downloaded the project and ran in my android device v4.4 kitkat, After downloading my own voice in file manager flite data path.Then I clicked on ttsdemo, then app is getting closed, I checked in the log it shows Not able to load library, findlibrary returned null, I am working in windows machine.I ran the Android.mk using ndk-build, but it didn't builded, and not builded libttsflite.so file.How can I make .so file from these .cc files. or how can I run direct .cc file from android. I am not familiar with android ndk build.I downloaded the flite-release code and in that there is no build folder,.configure file.Is it support to run in windows?,Is it possible to share the .so file to include in my project.

**Comment by happyalu** [comment]
Sorry, I don't have instructions for crosscompiling Flite under Windows. If you have figured it out, please share the steps. Otherwise I'd recommend using a linux machine or VM to build the app.
