### ISSUE TITLE
building Bengali voice

### ISSUE THREAD

**Issue by imty1000** [happyalu/Flite-TTS-Engine-for-Android#72]
Dear Sir,
I have been trying to build the Bengali voice for flite, i have followed http://festvox.org/bsv/x3528.html, but i am stuck at 
./bin/do_clustergen parallel f0_v_sptk
when i pass it i get this error
Failed to process ben_0991
./bin/make_f0_v_sptk: 128: ./bin/make_f0_v_sptk: /home/abk/Downloads/SPTK-3.10/bin/x2x: Permission denied
NB: ben_0991 is the 0991 th recorded voice and this happens for all the other recorded voices
please help

**Comment by happyalu** [comment]
The error seems to suggest SPTK isn't installed properly. Check that you can manually run  /home/abk/Downloads/SPTK-3.10/bin/x2x

Please contact the festvox mailing list for questions about building voices.

Closing this, since this is not an issue related to the app.
